### ISSUE TITLE
Tooltips are difficult to read near the bottom of the text

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias-web#19]
**Describe the bug**
When a tooltip appears near the bottom of the text display field, it overlaps with text underneath the text display and is difficult to read.

**To Reproduce**
1. Open the app in a web browser;
2. Paste in the [example letter of recommendation for a woman](https://github.com/gender-bias/gender-bias/blob/master/example_letters/letterofRecW);
3. Click **Submit**;
3. Scroll down to the bottom;
4. Mouse over both instances of the word "commitment."

**Expected behavior**
The tooltip should have a solid background and appropriate margins/padding so the text does not overlap.

**Screenshots**
![Screen Shot 2020-06-23 at 1 17 29 PM](https://user-images.githubusercontent.com/19829843/85457642-1eb13900-b555-11ea-8c37-345fe38ae8c6.png)
![Screen Shot 2020-06-23 at 1 16 45 PM](https://user-images.githubusercontent.com/19829843/85457655-21ac2980-b555-11ea-806d-607080bc4205.png)

**Desktop (please complete the following information):**
 - OS: MacOS Catalina (10.15.3)
 - Browser: Chrome 
 - Version 80.0.3987.132

**Comment by ProfJanetDavis** [comment]
This is almost certainly a problem with the styling on the tooltip that can be resolved entirely in CSS.

**Comment by j6k4m8** [comment]
@ProfJanetDavis should have a fix ready to go in #21 :)

**Comment by ProfJanetDavis** [comment]
Thanks @j6k4m8 ! We tested your fix and the problem is indeed resolved.
