### ISSUE TITLE
Remove empty tooltip at start of letter

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias-web#22]
**Describe the bug**
A space appears at the beginning of the output. Hovering over that space reveals an empty tooltip.

**To Reproduce**
1. Open the app in a web browser
2. Type anything in the text input area 
3. Click **Submit**
4. Observe the problem described above.

**Expected behavior**
I do not expect to see a space or an empty tooltip at the beginning of the output.

**Screenshots**
![Screen Shot 2020-06-25 at 4 41 40 PM](https://user-images.githubusercontent.com/19829843/85806221-47773100-b703-11ea-9d20-da1b8f533ad2.png)

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.3
 - Browser: Chrome
 - Version: 80.0.3987.132

**Additional context**
This bug occurs with the updated server as of [PR#67](https://github.com/gender-bias/gender-bias/pull/67)

**Comment by ProfJanetDavis** [comment]
We have a hypothesis about how to fix this! In `src/components/Readout.vue`, delete the following lines of code:

```
                    let flags = [
                        {
                            start: 0,
                            end: 0,
                            category: "",
                            issue: ""
                        }
                    ];
```

**Comment by j6k4m8** [comment]
Aha — yep! That's the offender. 

I think this was included to avoid flags=undefined, but I think that's spurious now.

(I think you mentioned this already, but the space is rendering because there's a tooltip there, which adds an additional `<span></span>` to the DOM. If we have flags pointing to text of zero length anywhere in the doc, we'll get this extra space. I think there's a CSS way to fix this but it may mess up tooltip positioning. I recall having a reason for letting it be this way, but I can't remember what it was now, and of course I naturally didn't write it down anywhere.)

**Comment by ProfJanetDavis** [comment]
Thanks, Jordan! It makes sense we don't want `flags=undefined`, but it seems like we could just initialize `flags` to an empty list instead. 

Since the fix is to delete a small amount of nearby code, I'm going to suggest to my team that we tackle this along with #10.

**Comment by ProfJanetDavis** [comment]
@j6k4m8, it turns out this fix doesn't work! If we delete that first empty flag, then we don't see any of the input text, up to the point of the first real flag. For example, see this screenshot:
![Screen Shot 2020-06-26 at 11 38 14 AM](https://user-images.githubusercontent.com/19829843/85890112-970c3a00-b7a1-11ea-802e-e7d7ec525ff8.png)

If there are no "real" flags, then no text appears at all, which is super confusing:
![Screen Shot 2020-06-26 at 11 40 13 AM](https://user-images.githubusercontent.com/19829843/85890251-d6d32180-b7a1-11ea-96e2-032c510ca7b7.png)

@elsayeaa suggests that we leave the empty flag at the start of the list of flags, and then just don't render the initial empty flag in the `Blurb`component. Does that make sense to you, Jordan, or would you suggest a different plan?
