### ISSUE TITLE
Remove unused component TextChecker

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias-web#23]
@j6k4m8, it looks like [`src/components/TextChecker.vue`](https://github.com/gender-bias/reading-for-genderbias-web/blob/master/src/components/TextChecker.vue) is not used anywhere. Is that correct? If so, I propose we remove the file.

**Comment by j6k4m8** [comment]
Yep that's correct. (This was subsumed when I merged with the older codebase, and I must have forgotten to take it out.)
