### ISSUE TITLE
Rename this repository to gender-bias-web

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias-web#30]
**Is your feature request related to a problem? Please describe.**
The name of this repository is long and cumbersome. This became evident when trying to name the new repository proposed in #29. It's also confusing that the name of this repository is hyphenated differently than that of the main `gender-bias` repo.

**Describe the solution you'd like**
This repository should be renamed to just `gender-bias-web`. 

**Describe alternatives you've considered**
The name `genderbias-web` is a little shorter but the hyphenation is still inconsistent. The repo name `gender-bias` is fine and we shouldn't mess with it. 

**Additional context**
After renaming, everyone with a local clone will need to [change their remote url](https://docs.github.com/en/github/using-git/changing-a-remotes-url).

**Comment by j6k4m8** [comment]
Done — those with local clones of this repo can continue using their current remotes (it will auto-redirect) but I definitely recommend changing when you (ustedes) get a chance!
