### ISSUE TITLE
After submission, each word becomes a separate blurb element. 

### ISSUE THREAD

**Issue by elsayeaa** [gender-bias/gender-bias-web#32]
**Description**
After submitting the recommendation letter, each word, including spaces, is transformed into a blurb component. This takes a lot of memory space in order to be displayed. 

**To Reproduce**
1. Write your recommendation letter in the text area
2. Click on the Submit button
3. Inspect the web-page and hover over each word. 
4. See that each word became a blurb component. 

**Expected behavior**
Tooltips are shown in flagged words; however, the text-area stays as one component.

**Suggested Fix** 

1. Add the entire text into a paragraph element, and only put the flagged words in the blurb component, and make the blurb component inside the paragraph component. For example: 

```
<p> She is <Blurb> willing </Blurb> to participate in X, and she is <Blurb> Committed </Blurb> to make the most of it. </p> 
```

**Comment by ProfJanetDavis** [comment]
Thanks for writing this up, @elsayeaa! That is one possible fix. Another one would be to join the words between flags into long, multi-word Blurb components. I'm not sure which approach is better. I'm curious how the current implementation would handle a multi-word phrase being contained in a single flag.

**Comment by ProfJanetDavis** [comment]
@j6k4m8, we have a question that I hope you can address. We were not sure if this is a back-end or a front-end issue. As I think about it more, and in particular as I think about how the JSON objects are constructed, I really think it's a front-end issue and should be filed there. Do you agree?

**Comment by j6k4m8** [comment]
Can you elaborate on the memory issue you encountered? (Browsers are surprisingly good at dense HTML DOMs, so if you're encountering a RAM issue it's probably a JavaScript bug!)

This is unfortunately starting to touch upon the difficulty of rendering overlapping flags; this, for example, is really hard to represent in HTML:


```
Here is my text. It has two problems in it.
PROB 1:           [---------------------]
PROB 2:                      [--------------]
```

I'd be very excited to discuss potential fixes for this! But I warn ye, here be dragons.... :)

**Comment by j6k4m8** [comment]
I just pulled the latest `master` and tried this — I'm not encountering the same issue. Here's what I see:

(I've added a cyan border around each blurb so you can see their delims)

<img width="776" alt="image" src="https://user-images.githubusercontent.com/693511/87727346-d15c6c00-c78e-11ea-9717-9b7c973b18de.png">

i.e. there are three blurbs here; one for `This is a`, one for `willing` (problematic cutout), and one for `paragraph. How fun! ... Another one follows.`

I think this is the behavior that  you wanted as the fix in the *Suggested Fix* in the issue report..?

**Comment by ProfJanetDavis** [comment]
I agree with @j6k4m8 's assessment of this issue.
