### ISSUE TITLE
Refactoring the submit button code in Main.vue

### ISSUE THREAD

**Issue by elsayeaa** [gender-bias/gender-bias-web#41]
**Problem**
In the submit button code on lines 16-22 in Main.vue: 
```
<button class="button is-info is-fullwidth submit-button"
   v-on:click="renderIssues(); showSidebar();
   hideHeader(); changeWidth()"
> 
Submit 
</button>
```
The ```v-on:click``` method calls multiple functions in a non-efficient, non-elegant way. 

**Suggested Change**

We should replace```ShowSidebar(); hideHeader(); changeWidth()``` with internal coding inside the RenderIssues() method, make it more appealing and concise. 

**Alternatives**
1 - Define each function inside ```RenderIssues()``` and call these functions at the end. 
2 - Make another function called ```applyChanges()``` and make it as a parent function for the changes. 
3 -  utilize conditional styling using Vue to apply such changes instead of writing more functions.

**Comment by ProfJanetDavis** [comment]
Resolved in PR #46, blocked on issue #47
