### ISSUE TITLE
Refactor and add to the Test Suite

### ISSUE THREAD

**Issue by dylanjwu** [gender-bias/gender-bias-web#42]
**Problem**

There is currently one pending test in `Main.spec.js` that still needs to be written. Additionally, the readability, functionality, and completeness of the entire automated test suite needs to be inspected and likely amended.

**Suggested changes**

This task might include declaring global variables within `bootstrap.js`, writing clear comments when necessary, removing unnecessary tests, and writing the pending test and any essential tests that we missed. In addition to making the test code more readable for future contributors, some documentation on how to write tests is also needed.

**Comment by ProfJanetDavis** [comment]
Resolved in PR #46; blocked on issue #47
