### ISSUE TITLE
Back-end server url should not be hard-coded

### ISSUE THREAD

**Issue by ProfJanetDavis** [gender-bias/gender-bias-web#48]
As a developer, I want to be able to run the web front-end against a back-end server running on `localhost`.

This is not possible with the URL hard-coded as a constant as shown below. It should be an argument when you run the server, or it should be stored in a configuration file.

https://github.com/gender-bias/gender-bias-web/blob/7cfc7a321ad43c44f72648879321642dcbf8c2be/src/components/Main.vue#L67

**Comment by j6k4m8** [comment]
See also #40 for a potential implementation strategy

**Comment by ProfJanetDavis** [comment]
This is a duplicate of #40 .
